platform:
  - x64

configuration:
  - Release

environment:
  BOOST_FILENAME_VERSION: 1_67_0
  BOOST_VERSION: 1.67.0

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 140
      VISUAL_STUDIO_VERSION: 14.0
      QT_BUILD: msvc2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
      VISUAL_STUDIO_INTERNAL_VERSION: 141
      VISUAL_STUDIO_VERSION: 14.1
      QT_BUILD: msvc2017

init:
  - cmake --version
  - msbuild /version

  - if [%platform%]==[x64] ( set "ARCHITECTURE=64" ) else ( set "ARCHITECTURE=32" )
  - if [%platform%]==[x64] ( set "CMAKE_GENERATOR_SUFFIX= Win64" )
  - set "GENERATOR_NAME=%CMAKE_GENERATOR%%CMAKE_GENERATOR_SUFFIX%"
  - set "LIB_ARCHITECTURE=lib%ARCHITECTURE%"
  - set "BOOST_ROOT=C:\Libraries\boost_%BOOST_FILENAME_VERSION%"
  - set "BOOST_INCLUDEDIR=%BOOST_ROOT%"
  - set "BOOST_LIBRARYDIR=%BOOST_ROOT%\%LIB_ARCHITECTURE%-msvc-%VISUAL_STUDIO_VERSION%"
  - set PATH=C:\Qt\5.11\%QT_BUILD%\bin;%PATH%

install:
  - git submodule update --init --recursive
  - call ci\appveyor-echo-environment.bat

before_build:
  - md build
  - cd build
  - cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBoost_USE_STATIC_LIBS=ON -DBOOST_LIBRARYDIR=%BOOST_LIBRARYDIR% ..

build:
  project: build/core8-emulator.sln
  parallel: true
  verbosity: quiet

test_script:
  - ctest -C %configuration% -VV .
