language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gcc-4.9
      env:
        - COMPILER_CXX=g++-4.9
        - COMPILER_CC=gcc-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
        - COMPILER_CXX=g++-5
        - COMPILER_CC=gcc-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env:
        - COMPILER_CXX=g++-6
        - COMPILER_CC=gcc-6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang++-3.6
            - clang-3.6
      env:
        - COMPILER_CXX=clang++-3.6
        - COMPILER_CC=clang-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang++-3.7
            - clang-3.7
      env:
        - COMPILER_CXX=clang++-3.7
        - COMPILER_CC=clang-3.7

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER_CXX=clang++

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER_CXX=clang++

sudo: required
dist: trusty

before_install:
  - source ci/travis-environment.sh
  - ci/travis-system-info.sh
  - ci/travis-before-install.sh

script:
  - ci/travis-script.sh

after_success:
  - ci/travis-after-success.sh

notifications:
  email: false
