language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10
      env: MATRIX_EVAL="brew install qt" BUILD_TYPE=Release

    - os: linux
      addons: { apt: {
        packages: [ g++-6, libboost1.55-all-dev, qt5-default ],
        sources: [ ubuntu-toolchain-r-test, boost-latest ] } }
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" BUILD_TYPE=Release

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ci/travis-script.sh

notifications:
  email: false
