language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang++

sudo: required
dist: trusty

before_install:
  - ci/travis-system-info.sh
  - ci/travis-before-install.sh

script:
  - ci/travis-script.sh

notifications:
  email: false
