language: cpp

matrix:
  include:
    # ---------------------------------------------------------------------------------------------
    # osx appleclang 10

    - os: osx
      osx_image: xcode10
      env: MATRIX_EVAL="brew install qt" BUILD_TYPE=Release

    - os: osx
      osx_image: xcode10
      env: MATRIX_EVAL="brew install qt" BUILD_TYPE=Debug

    # ---------------------------------------------------------------------------------------------
    # linux gcc-6 with coverage

    - os: linux
      addons: { apt: {
        packages: [ g++-6, libboost1.55-all-dev, qt5-default ],
        sources: [ ubuntu-toolchain-r-test, boost-latest ] } }
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" BUILD_TYPE=Release

    - os: linux
      addons: { apt: {
        packages: [ g++-6, libboost1.55-all-dev, qt5-default, lcov ],
        sources: [ ubuntu-toolchain-r-test, boost-latest ] } }
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" BUILD_TYPE=Coverage GCOV=gcov-6

    # ---------------------------------------------------------------------------------------------
    # linux clang-6

    - os: linux
      addons: &linux-clang-6 { apt: {
        packages: [ clang-6.0, libstdc++-6-dev, libboost1.55-all-dev, qt5-default ],
        sources: [ llvm-toolchain-trusty-6.0, ubuntu-toolchain-r-test, boost-latest ] } }
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Release

    - os: linux
      addons: *linux-clang-6
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Debug

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ci/travis-build.sh

after_success:
  - ci/travis-coverage.sh

notifications:
  email: false
