@echo off

echo ARCHITECTURE=%ARCHITECTURE%
echo CMAKE_GENERATOR_SUFFIX=%CMAKE_GENERATOR_SUFFIX%
echo GENERATOR_NAME=%GENERATOR_NAME%
echo LIB_ARCHITECTURE=%LIB_ARCHITECTURE%
echo BOOST_ROOT=%BOOST_ROOT%
echo BOOST_INCLUDEDIR=%BOOST_INCLUDEDIR%
echo BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR%

echo "Available libraries:"
dir C:\Libraries\
dir C:\Qt\
