name: continuous-integration

on: [push]

jobs:
  jobs_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        build_type: [Debug]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          target: 'desktop'

      - name: Create build directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{ matrix.build_type }} --verbose

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --build-config ${{ matrix.build_type }} --extra-verbose .
