name: cpp-linter

on:
  pull_request:
    paths: ['**.cpp', '**.hpp', '**CMakeLists.txt', '**.cmake']
  push:
    paths: ['**.cpp', '**.hpp', '**CMakeLists.txt', '**.cmake']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          thread-comments: false
          ignore: build

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed"
          echo "total checks-failed: ${{ steps.linter.outputs.checks-failed }}"
          echo "clang-tidy checks-failed: ${{ steps.linter.outputs.clang-tidy-checks-failed }}"
