name: build

on: [push]

jobs:
  jobs_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-22.04
            platform_version: 22.04
            link: static+shared
            toolset: gcc
          - os: macos-13
            platform_version: 13
            link: static+shared
            toolset: clang
          - os: windows-2022
            platform_version: 2022
            link: static
            toolset: msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo and download LFS dependencies
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: ${{ matrix.platform_version }}
          link: ${{ matrix.link }}
          toolset: ${{ matrix.toolset }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          target: 'desktop'

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          cmake --build . --config ${{ matrix.build_type }}
          ctest -C ${{ matrix.build_type }} -VV .
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
