name: build

on: [push]

jobs:
  jobs_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          target: 'desktop'

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.build_type }} -VV .
